### ISSUE TITLE
Sorting Improvements

### ISSUE THREAD

**Issue by stramel** [Buuntu/react-final-table#28]
Hello! 👋🏼 

Just started to look into this lib and noticed some various low-hanging fruit for improvements. The first of which would be sorting.

Currently, you allow for a custom sort(compare) function to be passed in via the column. This is a great first step for allowing customization in sorting.

There are 2 things that I see that could be improved.

1. Duplicated sorting logic in the case no custom sort is provided. This can be easily fixed by defaulting the column sort property to the default sort. ie.
```js
const columnCompareFn = column.sort || byTextAscending((object) => object.original[action.columnName]);
```

2. Currently, custom descending sorts require 2 passes over the array in order to properly sort. `.sort(column.sort).reverse()`. This could be implemented in a single pass by inverting the returned number. ie:

```js
data.sort((a, b) => {
  const result = compareFn(a, b);
  return isAscending ? result : result * -1;
})
```

Perf test: https://jsbench.me/45kmfbx99h/1

Another thing I had thought about was providing `isAscending` as an option to the compareFn to allow the user to handle that as they please.

```js
data.sort((a, b) => compareFn(a, b, isAscending))
```

Look forward to discussing this further and hearing your feedback @Buuntu! I'm more than happy to submit PRs for any of the changes.

/cc @cfsdfields

**Comment by Buuntu** [comment]
These sound like good improvements to me.  If you want to open a PR I would take a look!
